// js/productItems.js
// Datos de los productos de SurtiEnvases
const productItems = [
  {
    id: 1,
    title: "Frasco de Vidrio 250ml",
    price: "$2.500",
    origin: "Nacional",
    material: "Vidrio Tipo III",
    category: "Alimentos",
    description:
      "Frasco de vidrio transparente ideal para conservas, mermeladas y salsas.",
    img: "assets/img/productos/frasco-vidrio-250.jpg",
    isPopular: true,
    recommendation:
      "Perfecto para pequeños emprendimientos de conservas artesanales. Incluye tapa twist-off.",
    benefits: ["Apto para alimentos", "Esterilizable", "Reutilizable"],
    specifications: ["Capacidad: 250ml", "Boca: 63mm", "Altura: 110mm"],
    minimumOrder: "Caja x 24 unidades",
    category: "Envases de Vidrio",
    industry: "Alimentos",
    certification: "FDA Approved",
    stock: "Disponible",
  },
  {
    id: 2,
    title: "Botella PET 500ml",
    price: "$850",
    origin: "Nacional",
    material: "PET Cristal",
    category: "Bebidas",
    description:
      "Botella PET transparente con tapa rosca, ideal para jugos y bebidas.",
    img: "assets/img/productos/botella-pet-500.jpg",
    isPopular: true,
    recommendation:
      "La opción más económica para envasar bebidas. Excelente claridad y resistencia.",
    benefits: ["Ligero", "Irrompible", "100% Reciclable"],
    specifications: ["Capacidad: 500ml", "Rosca: 28mm", "Peso: 25g"],
    minimumOrder: "Paquete x 50 unidades",
    category: "Envases Plásticos",
    industry: "Bebidas",
    certification: "ISO 9001",
    stock: "Disponible",
  },
  {
    id: 3,
    title: "Tarro Cosmético 50g",
    price: "$3.200",
    origin: "Importado",
    material: "PP Premium",
    category: "Cosmética",
    description:
      "Tarro de alta calidad con doble pared para cremas y productos cosméticos.",
    img: "assets/img/productos/tarro-cosmetico-50.jpg",
    isPopular: false,
    recommendation:
      "Diseño elegante que realza la presentación de productos premium.",
    benefits: ["Doble pared", "Sellado hermético", "Diseño premium"],
    specifications: [
      "Capacidad: 50g",
      "Diámetro: 65mm",
      "Color: Transparente/Negro",
    ],
    minimumOrder: "Caja x 100 unidades",
    category: "Envases Cosméticos",
    industry: "Cosmética",
    certification: "INVIMA",
    stock: "Disponible",
  },
  {
    id: 4,
    title: "Galón Industrial 4L",
    price: "$4.800",
    origin: "Nacional",
    material: "HDPE Alta Densidad",
    category: "Industrial",
    description:
      "Galón resistente para productos químicos y de limpieza industrial.",
    img: "assets/img/productos/galon-industrial-4l.jpg",
    isPopular: false,
    recommendation:
      "Resistente a químicos, ideal para productos de limpieza y desinfectantes.",
    benefits: ["Alta resistencia química", "Manija ergonómica", "Graduado"],
    specifications: [
      "Capacidad: 4 Litros",
      "Boca: 38mm",
      "Color: Natural/Blanco",
    ],
    minimumOrder: "Paquete x 25 unidades",
    category: "Envases Industriales",
    industry: "Químicos",
    certification: "UN Approved",
    stock: "Disponible",
  },
  {
    id: 5,
    title: "Frasco Farmacéutico Ámbar 100ml",
    price: "$1.800",
    origin: "Importado",
    material: "Vidrio Ámbar Tipo I",
    category: "Farmacéutico",
    description:
      "Frasco ámbar que protege de la luz UV, ideal para medicamentos.",
    img: "assets/img/productos/frasco-ambar-100.jpg",
    isPopular: true,
    recommendation:
      "Cumple todas las normas farmacéuticas. Protección UV garantizada.",
    benefits: ["Protección UV", "Grado farmacéutico", "Hermético"],
    specifications: ["Capacidad: 100ml", "Rosca: DIN18", "Color: Ámbar"],
    minimumOrder: "Caja x 48 unidades",
    category: "Envases Farmacéuticos",
    industry: "Farmacéutica",
    certification: "USP Standards",
    stock: "Disponible",
  },
  {
    id: 6,
    title: "Tapa Twist-Off 63mm",
    price: "$180",
    origin: "Nacional",
    material: "Hojalata",
    category: "Tapas",
    description:
      "Tapa metálica con botón de seguridad para frascos de conserva.",
    img: "assets/img/productos/tapa-twist-63.jpg",
    isPopular: false,
    recommendation:
      "Compatible con todos nuestros frascos de boca 63mm. Sellado al vacío garantizado.",
    benefits: ["Botón de seguridad", "Recubrimiento interno", "Reutilizable"],
    specifications: [
      "Diámetro: 63mm",
      "Color: Dorado/Plateado",
      "Con pasteurización",
    ],
    minimumOrder: "Bolsa x 100 unidades",
    category: "Tapas y Complementos",
    industry: "Alimentos",
    certification: "FDA Approved",
    stock: "Disponible",
  },
  {
    id: 7,
    title: "Botella Spray 250ml",
    price: "$2.100",
    origin: "Nacional",
    material: "PET + Atomizador",
    category: "Limpieza",
    description:
      "Botella con atomizador ajustable para productos de limpieza y jardinería.",
    img: "assets/img/productos/botella-spray-250.jpg",
    isPopular: true,
    recommendation:
      "Atomizador de alta calidad con múltiples configuraciones de spray.",
    benefits: ["Atomizador ajustable", "Resistente a químicos", "Ergonómico"],
    specifications: ["Capacidad: 250ml", "Trigger spray", "Colores variados"],
    minimumOrder: "Paquete x 24 unidades",
    category: "Envases con Dispensador",
    industry: "Limpieza",
    certification: "ISO 9001",
    stock: "Disponible",
  },
  {
    id: 8,
    title: "Frasco Gotero 30ml",
    price: "$1.500",
    origin: "Importado",
    material: "Vidrio + Gotero",
    category: "Farmacéutico",
    description:
      "Frasco con gotero de precisión para aceites esenciales y medicamentos.",
    img: "assets/img/productos/frasco-gotero-30.jpg",
    isPopular: false,
    recommendation:
      "Ideal para aceites esenciales, tinturas y medicamentos líquidos.",
    benefits: ["Gotero de precisión", "Vidrio resistente", "Tapa de seguridad"],
    specifications: [
      "Capacidad: 30ml",
      "Pipeta de vidrio",
      "Color: Transparente/Ámbar",
    ],
    minimumOrder: "Caja x 100 unidades",
    category: "Envases Especializados",
    industry: "Farmacéutica/Cosmética",
    certification: "INVIMA",
    stock: "Disponible",
  },
  {
    id: 9,
    title: "Contenedor 1000ml Hermético",
    price: "$3.500",
    origin: "Nacional",
    material: "PP + Silicona",
    category: "Alimentos",
    description: "Contenedor hermético con cierre de seguridad para alimentos.",
    img: "assets/img/productos/contenedor-1000.jpg",
    isPopular: true,
    recommendation:
      "Sistema de cierre hermético con 4 pestañas. Apto para microondas y congelador.",
    benefits: ["Hermético 100%", "Apto microondas", "Libre de BPA"],
    specifications: ["Capacidad: 1000ml", "Rectangular", "Apilable"],
    minimumOrder: "Caja x 36 unidades",
    category: "Contenedores",
    industry: "Alimentos",
    certification: "FDA Approved",
    stock: "Disponible",
  },
  {
    id: 10,
    title: "Bolsa Stand-Up 500g",
    price: "$450",
    origin: "Nacional",
    material: "Laminado Kraft",
    category: "Flexible",
    description: "Bolsa tipo doypack con zipper y ventana transparente.",
    img: "assets/img/productos/bolsa-standup-500.jpg",
    isPopular: true,
    recommendation:
      "Perfecta para café, snacks y productos gourmet. Excelente presentación en góndola.",
    benefits: ["Barrera de oxígeno", "Zipper resellable", "Base estable"],
    specifications: ["Capacidad: 500g", "Con ventana", "Válvula opcional"],
    minimumOrder: "Paquete x 100 unidades",
    category: "Empaques Flexibles",
    industry: "Alimentos",
    certification: "ISO 22000",
    stock: "Por encargo",
  },
];
// CRÍTICO: Exponer al window
window.productItems = productItems;
console.log(
  "✓ productItems.js cargado - " +
    productItems.length +
    " productos disponibles"
);
